// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/guil95/ports-service/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// RepositoryPort is an autogenerated mock type for the RepositoryPort type
type RepositoryPort struct {
	mock.Mock
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *RepositoryPort) FindByID(ctx context.Context, id string) (*domain.Port, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Port
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Port, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Port); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Port)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveBulk provides a mock function with given fields: ctx, port
func (_m *RepositoryPort) SaveBulk(ctx context.Context, port []domain.Port) error {
	ret := _m.Called(ctx, port)

	if len(ret) == 0 {
		panic("no return value specified for SaveBulk")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.Port) error); ok {
		r0 = rf(ctx, port)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepositoryPort creates a new instance of RepositoryPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryPort {
	mock := &RepositoryPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
